language: go

go:
- 1.20

# Place the repo at GOPATH/src/${go_import_path} to support PRs from forks.
go_import_path: github.com/m-lab/gcp-service-discovery

before_install:
- export COVERALLS_SERVICE_JOB_ID=$(TRAVIS_JOB_ID)
- export COVERALLS_SERVICE_NAME="gcp-service-discovery"
- go install github.com/mattn/goveralls@latest
- go install github.com/wadey/gocovmerge@latest

script:
# Run query "unit tests".
- go test -v -short -covermode=count -coverprofile=merge.cov ./...

# Publish to coveralls
- $HOME/gopath/bin/goveralls -coverprofile=merge.cov -service=travis-ci

# Verify that the docker image builds.
- docker build -t gcp-service-discovery .
