dist: focal

language: go

go:
- 1.20

# Place the repo at GOPATH/src/${go_import_path} to support PRs from forks.
go_import_path: github.com/m-lab/gcp-service-discovery

before_install:
- export COVERALLS_SERVICE_JOB_ID=$(TRAVIS_JOB_ID)
- export COVERALLS_SERVICE_NAME="gcp-service-discovery"
- go install github.com/mattn/goveralls@latest
- go install github.com/wadey/gocovmerge@latest
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
- docker version
# Run query "unit tests".
- go test -v -short -covermode=count -coverprofile=merge.cov ./...

# Publish to coveralls
- $HOME/gopath/bin/goveralls -coverprofile=merge.cov -service=travis-ci

# Verify that the docker image builds.
- docker build -t gcp-service-discovery .
